{
  imports = [
    ./auto-login.nix
    ./boot.nix
    ./email.nix
    ./font.nix
    ./games.nix
    ./i18n.nix
    ./nix.nix
    ./theme.nix
    ./app/creative.nix
    ./app/discord.nix
    ./app/firefox.nix
    ./app/git.nix
    ./app/kitty.nix
    ./app/multimedia.nix
    ./app/obs-studio.nix
    ./app/office.nix
    ./app/thunderbird.nix
    ./app/tmux.nix
    ./dev/latex.nix
    ./dev/jupyter.nix
    ./dev/arduino.nix
    ./dev/web.nix
    ./editor/neovim.nix
    ./networking/networkmanager.nix
    ./services/openssh.nix
    ./services/pipewire.nix
    ./services/printing.nix
    ./services/random-background
    ./shell/zsh.nix
    ./users/ben.nix
    ./wm/i3.nix
    ./xdg.nix
  ];
}
